# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: mypool


steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'Free Trial(caff6298-8437-4b70-a763-67f07c7676bc)'
    ScriptType: 'FilePath'
    ScriptPath: '../azbackup.ps1'
    errorActionPreference: 'silentlyContinue'